### ISSUE TITLE
ClinVar upload issues..

### ISSUE THREAD

**Issue by dnil** [Clinical-Genomics/preClinVar#114]
From `cust002`:
![image](https://github.com/Clinical-Genomics/scout/assets/758570/ba97c209-53b0-42f8-a930-a4a08657d314)

**Comment by northwestwitch** [comment]
The multipleConditionExplanation field parsing is fixed now and the new release or PreClinVar is deployed on prod now. After fixing the submission content (see my comment [here](https://github.com/Clinical-Genomics/preClinVar/pull/115#issuecomment-2072413645)), submission via API should work
