### ISSUE TITLE
Wrong Accession submitted in ClinVar tests

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/preClinVar#74]
Got this email this morning. It's something we should fix before the next release!

```
Hi Chiara,

Our developers reported this morning another three API test submissions that
failed because the variant description includes rs150008607 in the Accession
field. Please address this issue before continuing to submit tests. Do you
have any questions?
```

**Comment by dnil** [comment]
Great! And it would not show in the csv and interfere with manual submission? I didn't see any for a couple of vars I tried, but I didn't quite take the time to hunt it down. 😊

**Comment by northwestwitch** [comment]
I don't think so. The fields of the CSV files haven't changed. That key/value corresponds to the variantion IDs: https://www.ncbi.nlm.nih.gov/clinvar/docs/spreadsheet/#variation_ids
